version: "3"
services:
  smartscout:
    build:
      context: .
    container_name: testing
    volumes:
      - .:/opt/node_app/app:delegated
    ports:
      - 9001:9001
    environment:
      - PORT=9001
